export enum appPermissions{
    viewEvents = "viewEvents",
    bookEvent = "bookEvent",
    createEvent =  "createEvents",
    updateEvent = "updateEvent",
    viewClients = "viewClients",
    updateClients = "updateClients",
    viewSalesUsers = "viewSalesUsers",
    viewReceptionistUsers = "viewReceptionistUsers",
    viewFinanceUsers = "viewFinanceUsers",
    viewSettings = "viewSettings",
    viewFinance = "viewFinance",
    addUsers = "addUsers",
    updateUsers = "updateUsers",

    viewInvoices = "view_invoices",
    submitInvoices =  "submit_invoices",
    addInvoices = "add_invoices",
    deleteInvoices = "delete_invoices",
    editInvoices =  "edit_invoices",
    viewInvoicesDetails = "view_invoice_details",
    updateSettings = "update_settings",
    deleteUsers = "delete_users",
    assignUserRoles = 'assign_user_roles',
    manageRoles = "manage_roles",
}